FROM python:3.12.2-slim

RUN apt-get update && apt-get install -y cron dos2unix locales
WORKDIR /app
ENV TZ="Europe/Warsaw"
ENV PYTHONPATH=/app

RUN sed -i '/pl_PL.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG pl_PL.UTF-8
ENV LANGUAGE pl_PL:pl
ENV LC_ALL pl_PL.UTF-8

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./docker/cron_etl /etc/cron.d/cron_etl
RUN chmod 0644 /etc/cron.d/cron_etl
RUN dos2unix /etc/cron.d/cron_etl #remove \r that windows adds to the files and it causes issues on linux
RUN crontab /etc/cron.d/cron_etl

RUN touch /var/log/chat_etl.log
RUN touch /var/log/cron.log

CMD printenv > /etc/environment && cron && tail -f /var/log/chat_etl.log /var/log/cron.log