FROM python:3.12.2-slim

WORKDIR /app

ENV PYHTONUNBUFFERED=1
RUN apt-get update && apt-get install -y cron dos2unix locales tesseract-ocr ffmpeg libsm6 libxext6 zip unzip

#Install Roboto font for the jpg tables
RUN apt-get update && apt-get install -y fontconfig wget && rm -rf /var/lib/apt/lists/*
RUN wget -q https://github.com/google/fonts/raw/main/apache/roboto/Roboto%5Bwdth%2Cwght%5D.ttf -O /usr/share/fonts/truetype/roboto.ttf
RUN fc-cache -f -v
RUN fc-list | grep -i roboto

COPY requirements.txt .
RUN pip install -r requirements.txt
ENV TZ="Europe/Warsaw"
ENV PYTHONPATH=/app

RUN sed -i '/pl_PL.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG pl_PL.UTF-8
ENV LANGUAGE pl_PL:pl
ENV LC_ALL pl_PL.UTF-8

CMD ["python", "src/main.py"]